# Generated by Django 5.2.8 on 2025-11-22 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_agua_ml', models.IntegerField(default=3000, verbose_name='Meta de Água (ml)')),
                ('meta_sono_horas', models.FloatField(default=8.0, verbose_name='Meta de Sono (horas)')),
                ('meta_exercicio_min', models.IntegerField(default=60, verbose_name='Meta de Exercício (min)')),
                ('meta_refeicoes_qtd', models.IntegerField(default=5, verbose_name='Meta de Refeições (qtd)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_ml', models.IntegerField(verbose_name='Quantidade (ml)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('Caminhada', 'Caminhada'), ('Corrida', 'Corrida'), ('Musculação', 'Musculação'), ('Natação', 'Natação'), ('Ciclismo', 'Ciclismo'), ('Outro', 'Outro')], default='Outro', max_length=50)),
                ('duracao_minutos', models.IntegerField(verbose_name='Duração (min)')),
                ('intensidade', models.CharField(choices=[('Baixa', 'Baixa'), ('Moderada', 'Moderada'), ('Intensa', 'Intensa')], default='Moderada', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_refeicao', models.CharField(choices=[('Café da Manhã', 'Café da Manhã'), ('Almoço', 'Almoço'), ('Jantar', 'Jantar'), ('Lanche', 'Lanche')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='O que você comeu?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_sono', models.FloatField(verbose_name='Horas de Sono')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data do Sono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
